# Generated by Django 4.1.5 on 2023-02-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('count', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
            ],
        ),
    ]
