# Generated by Django 4.1.5 on 2023-02-10 10:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_price_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
