# Generated by Django 4.1.5 on 2023-02-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_image'),
        ('cart', '0003_remove_cartitem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='items.item'),
        ),
    ]
